---
name: 'Continuous Integration'
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    name: 'Cargo Test'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        toolchain-version:
          - 'stable'
          - '1.78.0'  # MSRV
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 1
      - name: 'Target Cache'
        uses: 'actions/cache@v3'
        env:
          cache-name: 'cargo-cache'
        with:
          key: "${{ env.cache-name }}-${{ matrix.toolchain-version }}-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}"
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
      - name: 'Install Toolchain'
        uses: 'dtolnay/rust-toolchain@v1'
        with:
          toolchain: "${{ matrix.toolchain-version }}"
      - name: 'Run Default Feature Tests'
        run: |
          cargo test
# Commented out until we have a man page to lint.
#  mandoc:
#    name: 'Lint Man Page'
#    runs-on: 'ubuntu-latest'
#    steps:
#      - name: 'Checkout'
#        uses: 'actions/checkout@v2'
#        with:
#          fetch-depth: 1
#      - name: 'Install mandoc'
#        run: |
#          sudo apt install mandoc
#      - name: 'Lint Man Page'
#        run: |
#          mandoc -T lint man/hcdl.1
